[[pages]]
path = "main.py"
name = "Langchain for CV"
icon = "🔗"

[[pages]]
name = "Playground"
icon = "🚁"
is_section = true

[[pages]]
path = "app/image_editor.py"
name = "Image Editor"
icon = "✏️" 

[[pages]]
path = "app/image_generator.py"
name = "Image Generator"
icon = "🌄" 